"""Pavillon d'un navire à partir du MMSI (Maritime Identification Digits, UIT).

Les trois premiers chiffres du MMSI identifient l'État d'immatriculation
(table UIT-R M.585). Extrait couvrant l'Afrique, l'Europe, les Amériques,
l'Asie maritime et les principaux pavillons de libre immatriculation.
"""

from __future__ import annotations

MID_PAYS: dict[str, tuple[str, str]] = {
    # Afrique
    "601": ("ZA", "Afrique du Sud"),
    "603": ("AO", "Angola"),
    "605": ("DZ", "Algérie"),
    "607": ("TF", "Terres australes françaises"),
    "608": ("IO", "Territoire britannique de l'océan Indien"),
    "609": ("BI", "Burundi"),
    "610": ("BJ", "Bénin"),
    "611": ("BW", "Botswana"),
    "612": ("CF", "Centrafrique"),
    "613": ("CM", "Cameroun"),
    "615": ("CG", "Congo"),
    "616": ("KM", "Comores"),
    "617": ("CV", "Cap-Vert"),
    "618": ("AQ", "Terre Adélie"),
    "619": ("CI", "Côte d'Ivoire"),
    "620": ("KM", "Comores"),
    "621": ("DJ", "Djibouti"),
    "622": ("EG", "Égypte"),
    "624": ("ET", "Éthiopie"),
    "625": ("ER", "Érythrée"),
    "626": ("GA", "Gabon"),
    "627": ("GH", "Ghana"),
    "629": ("GM", "Gambie"),
    "630": ("GW", "Guinée-Bissau"),
    "631": ("GQ", "Guinée équatoriale"),
    "632": ("GN", "Guinée"),
    "633": ("BF", "Burkina Faso"),
    "634": ("KE", "Kenya"),
    "635": ("AQ", "Antarctique"),
    "636": ("LR", "Libéria"),
    "637": ("LR", "Libéria"),
    "638": ("SS", "Soudan du Sud"),
    "642": ("LY", "Libye"),
    "644": ("LS", "Lesotho"),
    "645": ("MU", "Maurice"),
    "647": ("MG", "Madagascar"),
    "649": ("ML", "Mali"),
    "650": ("MZ", "Mozambique"),
    "654": ("MR", "Mauritanie"),
    "655": ("MW", "Malawi"),
    "656": ("NE", "Niger"),
    "657": ("NG", "Nigeria"),
    "659": ("NA", "Namibie"),
    "660": ("RE", "La Réunion"),
    "661": ("RW", "Rwanda"),
    "662": ("SD", "Soudan"),
    "663": ("SN", "Sénégal"),
    "664": ("SC", "Seychelles"),
    "665": ("SH", "Sainte-Hélène"),
    "666": ("SO", "Somalie"),
    "667": ("SL", "Sierra Leone"),
    "668": ("ST", "São Tomé-et-Principe"),
    "669": ("SZ", "Eswatini"),
    "670": ("TD", "Tchad"),
    "671": ("TG", "Togo"),
    "672": ("TN", "Tunisie"),
    "674": ("TZ", "Tanzanie"),
    "675": ("UG", "Ouganda"),
    "676": ("CD", "RD Congo"),
    "677": ("TZ", "Tanzanie"),
    "678": ("ZM", "Zambie"),
    "679": ("ZW", "Zimbabwe"),
    "242": ("MA", "Maroc"),
    # Europe
    "201": ("AL", "Albanie"),
    "203": ("AT", "Autriche"),
    "204": ("PT", "Açores"),
    "205": ("BE", "Belgique"),
    "206": ("BY", "Biélorussie"),
    "207": ("BG", "Bulgarie"),
    "209": ("CY", "Chypre"),
    "210": ("CY", "Chypre"),
    "211": ("DE", "Allemagne"),
    "212": ("CY", "Chypre"),
    "213": ("GE", "Géorgie"),
    "214": ("MD", "Moldavie"),
    "215": ("MT", "Malte"),
    "216": ("AM", "Arménie"),
    "218": ("DE", "Allemagne"),
    "219": ("DK", "Danemark"),
    "220": ("DK", "Danemark"),
    "224": ("ES", "Espagne"),
    "225": ("ES", "Espagne"),
    "226": ("FR", "France"),
    "227": ("FR", "France"),
    "228": ("FR", "France"),
    "229": ("MT", "Malte"),
    "230": ("FI", "Finlande"),
    "231": ("FO", "Îles Féroé"),
    "232": ("GB", "Royaume-Uni"),
    "233": ("GB", "Royaume-Uni"),
    "234": ("GB", "Royaume-Uni"),
    "235": ("GB", "Royaume-Uni"),
    "236": ("GI", "Gibraltar"),
    "237": ("GR", "Grèce"),
    "238": ("HR", "Croatie"),
    "239": ("GR", "Grèce"),
    "240": ("GR", "Grèce"),
    "241": ("GR", "Grèce"),
    "243": ("HU", "Hongrie"),
    "244": ("NL", "Pays-Bas"),
    "245": ("NL", "Pays-Bas"),
    "246": ("NL", "Pays-Bas"),
    "247": ("IT", "Italie"),
    "248": ("MT", "Malte"),
    "249": ("MT", "Malte"),
    "250": ("IE", "Irlande"),
    "251": ("IS", "Islande"),
    "252": ("LI", "Liechtenstein"),
    "253": ("LU", "Luxembourg"),
    "254": ("MC", "Monaco"),
    "255": ("PT", "Madère"),
    "256": ("MT", "Malte"),
    "257": ("NO", "Norvège"),
    "258": ("NO", "Norvège"),
    "259": ("NO", "Norvège"),
    "261": ("PL", "Pologne"),
    "262": ("ME", "Monténégro"),
    "263": ("PT", "Portugal"),
    "264": ("RO", "Roumanie"),
    "265": ("SE", "Suède"),
    "266": ("SE", "Suède"),
    "267": ("SK", "Slovaquie"),
    "268": ("SM", "Saint-Marin"),
    "269": ("CH", "Suisse"),
    "270": ("CZ", "Tchéquie"),
    "271": ("TR", "Turquie"),
    "272": ("UA", "Ukraine"),
    "273": ("RU", "Russie"),
    "274": ("MK", "Macédoine du Nord"),
    "275": ("LV", "Lettonie"),
    "276": ("EE", "Estonie"),
    "277": ("LT", "Lituanie"),
    "278": ("SI", "Slovénie"),
    "279": ("RS", "Serbie"),
    # Amériques
    "303": ("US", "États-Unis (Alaska)"),
    "304": ("AG", "Antigua-et-Barbuda"),
    "305": ("AG", "Antigua-et-Barbuda"),
    "306": ("CW", "Curaçao"),
    "307": ("AW", "Aruba"),
    "308": ("BS", "Bahamas"),
    "309": ("BS", "Bahamas"),
    "310": ("BM", "Bermudes"),
    "311": ("BS", "Bahamas"),
    "312": ("BZ", "Belize"),
    "314": ("BB", "Barbade"),
    "316": ("CA", "Canada"),
    "319": ("KY", "Îles Caïmans"),
    "321": ("CR", "Costa Rica"),
    "323": ("CU", "Cuba"),
    "325": ("DM", "Dominique"),
    "327": ("DO", "République dominicaine"),
    "329": ("GP", "Guadeloupe"),
    "330": ("GD", "Grenade"),
    "331": ("GL", "Groenland"),
    "332": ("GT", "Guatemala"),
    "334": ("HN", "Honduras"),
    "336": ("HT", "Haïti"),
    "338": ("US", "États-Unis"),
    "339": ("JM", "Jamaïque"),
    "341": ("KN", "Saint-Kitts-et-Nevis"),
    "343": ("LC", "Sainte-Lucie"),
    "345": ("MX", "Mexique"),
    "347": ("MQ", "Martinique"),
    "348": ("MS", "Montserrat"),
    "350": ("NI", "Nicaragua"),
    "351": ("PA", "Panama"),
    "352": ("PA", "Panama"),
    "353": ("PA", "Panama"),
    "354": ("PA", "Panama"),
    "355": ("PA", "Panama"),
    "356": ("PA", "Panama"),
    "357": ("PA", "Panama"),
    "358": ("PR", "Porto Rico"),
    "359": ("SV", "Salvador"),
    "361": ("PM", "Saint-Pierre-et-Miquelon"),
    "362": ("TT", "Trinité-et-Tobago"),
    "364": ("TC", "Îles Turques-et-Caïques"),
    "366": ("US", "États-Unis"),
    "367": ("US", "États-Unis"),
    "368": ("US", "États-Unis"),
    "369": ("US", "États-Unis"),
    "370": ("PA", "Panama"),
    "371": ("PA", "Panama"),
    "372": ("PA", "Panama"),
    "373": ("PA", "Panama"),
    "374": ("PA", "Panama"),
    "375": ("VC", "Saint-Vincent-et-les-Grenadines"),
    "376": ("VC", "Saint-Vincent-et-les-Grenadines"),
    "377": ("VC", "Saint-Vincent-et-les-Grenadines"),
    "378": ("VG", "Îles Vierges britanniques"),
    "379": ("VI", "Îles Vierges américaines"),
    "701": ("AR", "Argentine"),
    "710": ("BR", "Brésil"),
    "720": ("BO", "Bolivie"),
    "725": ("CL", "Chili"),
    "730": ("CO", "Colombie"),
    "735": ("EC", "Équateur"),
    "740": ("FK", "Îles Malouines"),
    "745": ("GF", "Guyane"),
    "750": ("GY", "Guyana"),
    "755": ("PY", "Paraguay"),
    "760": ("PE", "Pérou"),
    "765": ("SR", "Suriname"),
    "770": ("UY", "Uruguay"),
    "775": ("VE", "Venezuela"),
    # Asie / Océanie / Moyen-Orient
    "403": ("SA", "Arabie saoudite"),
    "405": ("BD", "Bangladesh"),
    "408": ("BH", "Bahreïn"),
    "412": ("CN", "Chine"),
    "413": ("CN", "Chine"),
    "414": ("CN", "Chine"),
    "416": ("TW", "Taïwan"),
    "419": ("IN", "Inde"),
    "422": ("IR", "Iran"),
    "425": ("IQ", "Irak"),
    "428": ("IL", "Israël"),
    "431": ("JP", "Japon"),
    "432": ("JP", "Japon"),
    "440": ("KR", "Corée du Sud"),
    "441": ("KR", "Corée du Sud"),
    "445": ("KP", "Corée du Nord"),
    "447": ("KW", "Koweït"),
    "450": ("LB", "Liban"),
    "455": ("MV", "Maldives"),
    "457": ("MN", "Mongolie"),
    "459": ("NP", "Népal"),
    "461": ("OM", "Oman"),
    "463": ("PK", "Pakistan"),
    "466": ("QA", "Qatar"),
    "468": ("SY", "Syrie"),
    "470": ("AE", "Émirats arabes unis"),
    "471": ("AE", "Émirats arabes unis"),
    "473": ("YE", "Yémen"),
    "475": ("YE", "Yémen"),
    "477": ("HK", "Hong Kong"),
    "501": ("AQ", "Terre Adélie"),
    "503": ("AU", "Australie"),
    "506": ("MM", "Myanmar"),
    "508": ("BN", "Brunei"),
    "510": ("FM", "Micronésie"),
    "511": ("PW", "Palaos"),
    "512": ("NZ", "Nouvelle-Zélande"),
    "514": ("KH", "Cambodge"),
    "515": ("KH", "Cambodge"),
    "516": ("CX", "Île Christmas"),
    "518": ("CK", "Îles Cook"),
    "520": ("FJ", "Fidji"),
    "523": ("CC", "Îles Cocos"),
    "525": ("ID", "Indonésie"),
    "529": ("KI", "Kiribati"),
    "531": ("LA", "Laos"),
    "533": ("MY", "Malaisie"),
    "536": ("MP", "Mariannes du Nord"),
    "538": ("MH", "Îles Marshall"),
    "540": ("NC", "Nouvelle-Calédonie"),
    "542": ("NU", "Niue"),
    "544": ("NR", "Nauru"),
    "546": ("PF", "Polynésie française"),
    "548": ("PH", "Philippines"),
    "553": ("PG", "Papouasie-Nouvelle-Guinée"),
    "555": ("PN", "Pitcairn"),
    "557": ("SB", "Îles Salomon"),
    "559": ("AS", "Samoa américaines"),
    "561": ("WS", "Samoa"),
    "563": ("SG", "Singapour"),
    "564": ("SG", "Singapour"),
    "565": ("SG", "Singapour"),
    "566": ("SG", "Singapour"),
    "567": ("TH", "Thaïlande"),
    "570": ("TO", "Tonga"),
    "572": ("TV", "Tuvalu"),
    "574": ("VN", "Viêt Nam"),
    "576": ("VU", "Vanuatu"),
    "577": ("VU", "Vanuatu"),
    "578": ("WF", "Wallis-et-Futuna"),
}

# MID des pavillons de libre immatriculation les plus fréquents (indicatif)
PAVILLONS_LIBRE_IMMATRICULATION: frozenset[str] = frozenset(
    {"PA", "LR", "MH", "BS", "MT", "AG", "VU", "KM", "TG", "SL", "CM", "BZ", "KN", "VC", "CK"}
)


def pavillon_from_mmsi(mmsi: str | None) -> tuple[str | None, str | None]:
    """(code ISO, nom) du pavillon, ou (None, None) si MMSI inconnu / non navire.

    Les MMSI de 9 chiffres commençant par 0 ou 1 (stations côtières, groupes,
    SAR aéronef) et les MMSI courts ne portent pas de pavillon exploitable.
    """
    if not mmsi:
        return None, None
    digits = "".join(ch for ch in str(mmsi) if ch.isdigit())
    if len(digits) != 9:
        return None, None
    if digits[0] in "01":
        return None, None
    if digits[0] == "8":  # pavillon handheld VHF / usage particulier
        digits = digits[1:]
    if digits[0] == "9" and digits[1] in "17":  # SAR / AtoN : MID en positions 3-5 ou 2-4
        return None, None
    mid = digits[:3]
    entry = MID_PAYS.get(mid)
    if entry is None:
        return None, None
    return entry


def pavillon_label(mmsi: str | None) -> str | None:
    code, nom = pavillon_from_mmsi(mmsi)
    if not code:
        return None
    return nom
